# Form implementation generated from reading ui file '.\interface\database_update_pd.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 305)
        Dialog.setWindowFlag(Qt.WindowMinimizeButtonHint, True)
        Dialog.setWindowFlag(Qt.WindowMaximizeButtonHint, True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress_label = QtWidgets.QLabel(parent=Dialog)
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout.addWidget(self.progress_label)
        self.progress_bar = QtWidgets.QProgressBar(parent=Dialog)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.log = QtWidgets.QListWidget(parent=Dialog)
        self.log.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.log.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.log.setProperty("showDropIndicator", True)
        self.log.setWordWrap(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.btn_box = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.btn_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.btn_box.setCenterButtons(False)
        self.btn_box.setObjectName("btn_box")
        self.verticalLayout.addWidget(self.btn_box)

        self.retranslateUi(Dialog)
        self.btn_box.accepted.connect(Dialog.accept) # type: ignore
        self.btn_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PSS Database Update"))
        self.progress_label.setText(_translate("Dialog", "Updating statuses:"))
